# Generated by Django 4.2.7 on 2023-11-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cidade",
            name="bairro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atalhos.bairro",
            ),
        ),
    ]
