# Generated by Django 4.2.7 on 2023-11-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0002_cidade_bairro"),
    ]

    operations = [
        migrations.AddField(
            model_name="estado",
            name="cidade_do_estado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atalhos.cidade",
            ),
        ),
    ]
