# Generated by Django 4.2.7 on 2023-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0004_rename_nome_do_estado_cidade_nome_do_cidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rua",
            name="numero",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rua",
            name="ponto_de_referencia",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
