# Generated by Django 4.2.7 on 2023-11-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0006_pais_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="endereço",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atalhos.estado",
            ),
        ),
        migrations.DeleteModel(
            name="Pais",
        ),
    ]
