# Generated by Django 4.2.7 on 2023-11-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0008_endereco_rua"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bairro",
            name="nome_da_rua",
        ),
        migrations.RemoveField(
            model_name="cidade",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="estado",
            name="cidade_do_estado",
        ),
        migrations.AddField(
            model_name="endereco",
            name="bairro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atalhos.bairro",
            ),
        ),
        migrations.AddField(
            model_name="endereco",
            name="cidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atalhos.cidade",
            ),
        ),
    ]
