# Generated by Django 4.2.7 on 2023-11-14 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0009_remove_bairro_nome_da_rua_remove_cidade_bairro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endereco",
            old_name="endereço",
            new_name="estado",
        ),
    ]
