# Generated by Django 4.2.7 on 2023-11-14 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0011_ddd"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DDD",
            new_name="DDD47",
        ),
    ]
