# Generated by Django 4.2.7 on 2023-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atalhos", "0012_rename_ddd_ddd47"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operadora",
                    models.CharField(
                        choices=[
                            ("VIVO", "Vivo"),
                            ("TIM", "TIM"),
                            ("CLARO", "Claro"),
                            ("OI", "Oi"),
                            ("NEXTEL", "Nextel"),
                            ("ALGAR", "Algar"),
                            ("SERCOMTEL", "Sercomtel"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
